import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

describe("release documentation", () => {
  it("documents the read-only boundary, supported commands, and profile evidence", async () => {
    const readme = await readFile("README.md", "utf8");
    const security = await readFile("docs/security-boundary.md", "utf8");
    const authoring = await readFile("docs/authoring-fixtures.md", "utf8");
    const compatibility = await readFile("docs/compatibility.md", "utf8");
    const runner = await readFile("docs/runner-contract.md", "utf8");
    const provenance = await readFile("docs/runner-provenance.md", "utf8");
    const adapter = await readFile("docs/provider-adapter.md", "utf8");
    const egress = await readFile("docs/egress-contract.md", "utf8");
    const remote = await readFile("docs/remote-lifecycle.md", "utf8");
    const dogfood = await readFile("docs/dogfood-2026-08-05.md", "utf8");
    const review = await readFile("docs/security-review-egress-provider-runtime.md", "utf8");
    const rollout = await readFile("docs/rollout-egress-provider-runtime.md", "utf8");
    const runtime = await readFile("docs/superpowers/specs/2026-08-05-egress-provider-runtime-design.md", "utf8");
    const readiness = await readFile("docs/release-readiness-2026-08-05.md", "utf8");
    const activationGate = await readFile("docs/runtime-activation-gate.md", "utf8");
    const credentialContract = await readFile("docs/credential-contract.md", "utf8");
    const ci = await readFile("docs/ci.md", "utf8");
    const runbook = await readFile("docs/runtime-operator-runbook.md", "utf8");
    const releaseWorkflow = await readFile(".github/workflows/release.yml", "utf8");
    const repositoryWorkflow = await readFile(".github/workflows/skillsync.yml", "utf8");
    const githubTemplate = await readFile("templates/github/skillsync.yml", "utf8");
    const preCommitTemplate = await readFile("templates/pre-commit/skillsync.yaml", "utf8");
    const packageJson = JSON.parse(await readFile("package.json", "utf8")) as {
      bugs?: { url?: string };
      homepage?: string;
      private?: boolean;
      repository?: { type?: string; url?: string };
    };

    expect(readme).toContain("verify");
    expect(readme).toContain("explain");
    expect(readme).toContain("fix --plan");
    expect(readme).toContain("fix --apply");
    expect(readme).toContain("report");
    expect(readme).toContain("applied");
    expect(readme).toContain("verified");
    expect(readme).toContain("manual resolutions are shown for review");
    expect(readme).toContain("never invent or overwrite user content");
    expect(readme).toContain("no Skill script is executed by this flow");
    expect(readme).toContain("不执行 Skill 脚本");
    expect(readme).toContain("include_local_paths");
    expect(readme).toContain("<local-path>");
    expect(security).toContain("not a security certification");
    expect(security).toContain("reporting.include_local_paths");
    expect(security).toContain("<local-path>");
    expect(security).toContain("Replay");
    expect(readme).toContain("--execute");
    expect(authoring).toContain("schema_version: 2");
    expect(authoring).toContain("--backend replay");
    expect(security).toContain("symlink");
    expect(compatibility).toContain("codex@1");
    expect(compatibility).toContain("claude-code@1");
    expect(compatibility).toContain("cursor@1");
    expect(compatibility).toContain("skillFolderHash");
    expect(readme).toContain("`npx skills` v3");
    expect(readme).toContain("runner validate");
    expect(readme).toContain("reference Runner");
    expect(security).toContain("workspace evidence");
    expect(runner).toContain("runner validate");
    expect(provenance).toContain("runner.signature-verification-unavailable");
    expect(readme).toContain("runner adapter validate");
    expect(readme).toContain("external runtime deployment requirements");
    expect(readme).toContain("--image skillsync/reference@sha256:");
    expect(readme).toContain("reference-adapter-policy.json");
    expect(adapter).toContain("explicit-short-lived");
    expect(adapter).toContain("external immutable image reference and an external identity policy");
    expect(runtime).toContain("allowlist");
    expect(runtime).toContain("credentials");
    expect(egress).toContain("allowlist");
    expect(egress).toContain("does not open sockets");
    expect(remote).toContain("cleaned");
    expect(remote).toContain("credentials");
    expect(remote).toContain("cleanup_proof");
    expect(remote).toContain("Ed25519");
    expect(remote).toContain("trusted Worker-key map");
    expect(dogfood).toContain("genkoy-component-splitter");
    expect(dogfood).toContain("rewrite them automatically");
    expect(review).toContain("Offline contract hardening complete");
    expect(review).toContain("retry contract missing");
    expect(rollout).toContain("Immediate rollback triggers");
    expect(rollout).toContain("direct network access");
    expect(readiness).toContain("本地发布候选状态");
    expect(readiness).toContain("独立安全复核");
    expect(readiness).toContain("Docker daemon 仍不可用");
    expect(activationGate).toContain("provider-credentials");
    expect(activationGate).toContain("不打开 socket");
    expect(activationGate).toContain("runtime-activation-boundary");
    expect(activationGate).toContain("authoritative: false");
    expect(activationGate).toContain("runtime-deployment-requirements.schema.json");
    expect(credentialContract).toContain("secret://");
    expect(credentialContract).toContain("不会解析宿主环境");
    expect(ci).toContain("skillsync-runtime-canary.yml");
    expect(ci).toContain("does not claim a live Worker");
    expect(ci).toContain("enable_live_capabilities");
    expect(ci).toContain("--pull=false");
    expect(ci).toContain("release.yml");
    expect(ci).toContain("offline-simulated");
    expect(runbook).toContain("Activation");
    expect(runbook).toContain("Revocation");
    expect(runbook).toContain("Rollback");
    expect(runbook).toContain("Evidence review");
    expect(runbook).toContain("RuntimeTrustRoot");
    expect(runbook).toContain("secret reference");
    expect(runbook).toContain("mTLS");
    expect(runbook).toContain("remote Worker");
    expect(releaseWorkflow).toContain('tags: ["v*"]');
    expect(releaseWorkflow).not.toContain("npm publish");
    expect(repositoryWorkflow).toContain("git grep -nE");
    expect(repositoryWorkflow).not.toContain("rg -n");
    expect(githubTemplate).toContain("skillsync@0.1.0");
    expect(preCommitTemplate).toContain("skillsync@0.1.0");
    expect(review).toContain("runtime-activation-policy.ts");
    expect(review).toContain("runtime-deployment-requirements.ts");
    expect(packageJson.private).toBe(true);
    expect(packageJson.repository).toEqual({
      type: "git",
      url: "https://github.com/Chumaniac/skillsync.git",
    });
    expect(packageJson.homepage).toBe("https://github.com/Chumaniac/skillsync#readme");
    expect(packageJson.bugs).toEqual({
      url: "https://github.com/Chumaniac/skillsync/issues",
    });
  });
});
